"""
Email Verification - Complete Reference & Test Suite

This file contains:
- Email template examples
- Test cases
- Common patterns
- Troubleshooting
"""

# ============================================================================
# EMAIL TEMPLATES
# ============================================================================

# These are auto-generated by email_manager.py, but here are the templates:

VERIFICATION_EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #FF006E 0%, #8338EC 100%); color: white; padding: 30px; border-radius: 8px 8px 0 0; text-align: center; }
        .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 8px 8px; }
        .button { background: #FF006E; color: white; padding: 12px 30px; text-decoration: none; border-radius: 4px; display: inline-block; margin: 20px 0; }
        .footer { color: #888; font-size: 12px; margin-top: 20px; }
        .code { background: #fff; padding: 10px; border-left: 4px solid #FF006E; font-family: monospace; margin: 10px 0; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>👥 Influencer Radar</h1>
            <p>Email Verification</p>
        </div>
        <div class="content">
            <p>Hi there! 👋</p>
            <p>Thanks for using Influencer Radar! Click the button below to verify your email address.</p>
            <p style="text-align: center;">
                <a href="{verification_link}" class="button">Verify Email Address</a>
            </p>
            <p>Or copy this link in your browser:</p>
            <div class="code">{verification_link}</div>
            <p style="color: #888; font-size: 12px;">
                This link expires in 24 hours. If you didn't request this email, you can ignore it.
            </p>
            <div class="footer">
                <p>© 2026 Influencer Radar. All rights reserved.</p>
                <p>Email: {email}</p>
            </div>
        </div>
    </div>
</body>
</html>
"""

PAYMENT_RECEIPT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #FF006E 0%, #8338EC 100%); color: white; padding: 30px; border-radius: 8px 8px 0 0; text-align: center; }
        .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 8px 8px; }
        .receipt { background: white; padding: 20px; border: 1px solid #ddd; border-radius: 4px; margin: 20px 0; }
        .row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #eee; }
        .label { color: #666; font-weight: bold; }
        .value { color: #333; }
        .total { font-size: 24px; color: #FF006E; font-weight: bold; margin-top: 10px; }
        .footer { color: #888; font-size: 12px; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>👥 Influencer Radar</h1>
            <p>Payment Receipt</p>
        </div>
        <div class="content">
            <p>Hi there! 👋</p>
            <p>Thank you for your purchase!</p>

            <div class="receipt">
                <div class="row">
                    <span class="label">Receipt #:</span>
                    <span class="value">{payment_id}</span>
                </div>
                <div class="row">
                    <span class="label">Date:</span>
                    <span class="value">{timestamp}</span>
                </div>
                <div class="row">
                    <span class="label">Item:</span>
                    <span class="value">{payment_type}</span>
                </div>
                <div class="row">
                    <span class="label">Amount:</span>
                    <span class="value">${amount}</span>
                </div>
                <div class="total">Total: ${amount}</div>
            </div>

            <p style="color: #888; font-size: 12px;">
                If you have any questions, contact support@influencerradar.app
            </p>

            <div class="footer">
                <p>© 2026 Influencer Radar. All rights reserved.</p>
            </div>
        </div>
    </div>
</body>
</html>
"""

# ============================================================================
# TEST CASES
# ============================================================================

def test_email_verification_complete_flow():
    """
    Complete test of email verification flow.
    Run this in a Streamlit app to test end-to-end.
    """
    import streamlit as st
    from modules.email_manager import EmailVerificationManager
    from modules.persistent_user_manager import PersistentUserManager

    st.title("Email Verification Test Suite")

    # Initialize managers
    user_manager = PersistentUserManager()
    email_manager = EmailVerificationManager(provider="test")

    # Test 1: Request verification
    st.subheader("Test 1: Request Verification")
    test_email = st.text_input("Test email", "test@example.com")

    if st.button("Request Verification"):
        success, message = email_manager.request_verification(
            test_email,
            user_manager.get_user_id()
        )
        st.write(f"Success: {success}")
        st.write(f"Message: {message}")

        # Extract token from message for testing
        if "verify_email=" in message:
            token = message.split("verify_email=")[1]
            st.session_state.test_token = token
            st.info(f"Token saved: {token[:10]}...")

    # Test 2: Verify token
    st.subheader("Test 2: Verify Token")

    if "test_token" in st.session_state:
        token = st.session_state.test_token

        if st.button("Verify Token"):
            success, message, data = email_manager.verify_email(token)

            st.write(f"Success: {success}")
            st.write(f"Message: {message}")

            if data:
                st.json(data)

                # Link email to user
                user_manager.set_verified_email(data["email"])
                st.success("Email linked to user!")

    # Test 3: Check status
    st.subheader("Test 3: Check Verification Status")

    status = email_manager.get_verification_status(user_manager.get_user_id())
    st.json(status)

    # Test 4: User manager integration
    st.subheader("Test 4: User Manager Integration")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.write(f"**Email:** {user_manager.get_email()}")

    with col2:
        st.write(f"**Verified:** {user_manager.is_email_verified()}")

    with col3:
        st.write(f"**Status:** {user_manager.get_email_verification_status()}")


def test_token_security():
    """Test token security features."""
    from modules.email_manager import SecureTokenManager
    import time

    manager = SecureTokenManager()

    # Test 1: Token generation
    token1 = manager.generate_token()
    token2 = manager.generate_token()
    assert token1 != token2, "Tokens should be unique"
    print(f"✅ Token generation: {token1[:10]}...")

    # Test 2: Token hashing
    hash1 = manager.hash_token(token1)
    hash2 = manager.hash_token(token1)
    assert hash1 == hash2, "Same token should produce same hash"
    print(f"✅ Hashing: {hash1[:10]}...")

    # Test 3: Token verification
    assert manager.verify_token(token1, hash1), "Should verify correct token"
    assert not manager.verify_token(token2, hash1), "Should reject wrong token"
    print("✅ Verification: Works correctly")

    # Test 4: Expiration
    now = "2026-01-01T10:00:00"
    assert not manager.is_token_expired(now), "Should not expire in future"
    print("✅ Expiration: Correct behavior")


def test_email_validation():
    """Test email validation."""
    from modules.email_manager import EmailVerificationManager

    manager = EmailVerificationManager(provider="test")

    valid_emails = [
        "test@example.com",
        "user+tag@domain.co.uk",
        "name123@sub.domain.com",
    ]

    invalid_emails = [
        "notanemail",
        "@example.com",
        "user@",
        "user @example.com",
        "",
    ]

    for email in valid_emails:
        assert manager._is_valid_email(email), f"Should accept {email}"
        print(f"✅ Valid: {email}")

    for email in invalid_emails:
        assert not manager._is_valid_email(email), f"Should reject {email}"
        print(f"✅ Rejected: {email}")


# ============================================================================
# COMMON PATTERNS
# ============================================================================

# Pattern 1: Send verification email when user opts in
def send_verification_email_on_opt_in():
    """Example: Send verification when user clicks button."""
    import streamlit as st
    from modules.email_manager import EmailVerificationManager

    email_manager = EmailVerificationManager()

    with st.form("email_form"):
        email = st.text_input("Email")
        submitted = st.form_submit_button("Verify Email")

        if submitted:
            success, message = email_manager.request_verification(
                email,
                user_id="user_123",
                app_url="https://myapp.streamlit.app"
            )

            if success:
                st.success(message)
            else:
                st.error(message)


# Pattern 2: Check verification status on app load
def check_email_verification_on_load():
    """Example: Show verification badge on load."""
    import streamlit as st
    from modules.email_manager import EmailVerificationManager

    email_manager = EmailVerificationManager()
    user_id = st.session_state.user_id

    status = email_manager.get_verification_status(user_id)

    if status["is_verified"]:
        st.success(f"✅ Verified: {status['email']}")
    else:
        st.info("Verify your email to unlock account recovery")


# Pattern 3: Send payment receipt to verified email
def send_payment_receipt():
    """Example: Send receipt after payment."""
    from modules.email_manager import get_payment_receipt_html
    from datetime import datetime

    verified_email = "user@example.com"  # From user_manager
    email_provider = None  # Your email provider instance

    # Generate receipt HTML
    html = get_payment_receipt_html(
        user_email=verified_email,
        payment_id="pay_123",
        amount=2.99,
        payment_type="analysis",
        timestamp=datetime.now().isoformat()
    )

    # Send email
    if email_provider:
        success = email_provider.send_email(
            to_email=verified_email,
            subject="Payment Receipt - Influencer Radar",
            html_content=html
        )


# ============================================================================
# TROUBLESHOOTING
# ============================================================================

TROUBLESHOOTING_GUIDE = """
Problem: "Email provider not initialized"
Solution:
  1. Check API key in .streamlit/secrets.toml
  2. Verify provider name is correct ("sendgrid" or "resend")
  3. Check for typos in API key
  4. Restart Streamlit app (Ctrl+C, then streamlit run app.py)

Problem: Verification email not received
Solution:
  1. Check spam folder
  2. Verify email address is correct
  3. Check email provider account has credits
  4. Enable debug panel: st.checkbox("Email Debug") → view logs
  5. Try test mode to see if link generates

Problem: Link expires too quickly
Solution:
  1. Check server time is correct
  2. Links expire after 24 hours (default)
  3. Can customize: SecureTokenManager.EXPIRATION_HOURS = 48

Problem: Can't verify same email twice
Solution:
  1. Tokens are one-time use (by design)
  2. To re-verify: request new verification
  3. Each verification gets a new token

Problem: Email not linked after verification
Solution:
  1. Check user_manager.set_verified_email() was called
  2. Verify PersistentUserManager is initialized
  3. Check browser storage is enabled
  4. Verify _save_user_data() was called

Problem: Verification status not persisting
Solution:
  1. Check persistent_user_manager fields:
     - email
     - is_email_verified
     - email_verified_at
  2. Verify storage backend is working
  3. Check debug panel for storage status
  4. Try running test_token_security() function
"""

# ============================================================================
# RUNNING TESTS
# ============================================================================

if __name__ == "__main__":
    print("Running Email Verification Tests...\n")

    print("Test 1: Token Security")
    test_token_security()
    print()

    print("Test 2: Email Validation")
    test_email_validation()
    print()

    print("✅ All tests passed!")
